# Homebrew formula for RIFT.
#
# This file lives at: Formula/rift.rb in the Nexstone/homebrew-tap repo.
# Users install via: brew install Nexstone/tap/rift
#
# IMPORTANT — this is the source-of-truth copy. The tap repo's copy must
# stay in sync. The release workflow auto-bumps the `version`, `url`, and
# `sha256` on every tag.

class Rift < Formula
  desc "Quant trading infrastructure for Hyperliquid (CLI + research + MCP server)"
  homepage "https://nexstone.io"
  # ── Versioned source — bumped automatically by .github/workflows/release.yml
  url "https://github.com/Nexstone/rift/archive/refs/tags/v0.1.2.tar.gz"
  sha256 "PLACEHOLDER_SHA256_AUTO_FILLED_BY_RELEASE_WORKFLOW"
  license "Apache-2.0"

  # ── Runtime dependencies
  depends_on "node@20"
  depends_on "python@3.13"

  def install
    # Pin the Python interpreter so the venv we create points at the same
    # python brew installed (not whatever 3.x happens to be first on PATH).
    python_bin = Formula["python@3.13"].opt_bin/"python3.13"
    npm_bin = Formula["node@20"].opt_bin/"npm"

    # ── 1. Python engine: create an isolated venv inside libexec and
    #    install rift-engine-core, the consolidated distribution that
    #    bundles all 10 internal namespace packages.
    venv = libexec/"python-venv"
    system python_bin, "-m", "venv", venv
    system venv/"bin/python", "-m", "pip", "install", "--upgrade", "pip", "wheel"
    system venv/"bin/python", "-m", "pip", "install", "rift-engine-core==#{version}"

    # ── 2. TS CLI: install globally into libexec so we don't pollute the
    #    user's global npm directory.
    npm_prefix = libexec/"npm"
    npm_prefix.mkpath
    ENV["NPM_CONFIG_PREFIX"] = npm_prefix
    system npm_bin, "install", "-g", "@nexstone/rift-cli@#{version}"

    # ── 3. Wrapper script that runs the CLI with the engine's venv on PATH.
    #    The TS CLI auto-detects `rift-engine` on PATH; setting
    #    RIFT_ENGINE_BINARY explicitly pins it to the libexec venv even if
    #    a stray rift-engine is installed elsewhere on the user's system.
    (bin/"rift").write <<~SHELL
      #!/usr/bin/env bash
      # Auto-generated by Homebrew. Do not edit by hand.
      export PATH="#{venv}/bin:#{Formula["node@20"].opt_bin}:$PATH"
      export RIFT_ENGINE_BINARY="#{venv}/bin/rift-engine"
      exec "#{npm_prefix}/bin/rift" "$@"
    SHELL
    chmod 0755, bin/"rift"
  end

  def post_install
    # Make sure ~/.rift exists so the user doesn't trip on `rift auth setup`
    # creating it with the wrong permissions.
    rift_home = Pathname.new(Dir.home)/".rift"
    rift_home.mkpath
    rift_home.chmod(0700)
  end

  def caveats
    <<~EOS
      RIFT installed. Next steps:

        1. Verify the install:
             rift doctor

        2. Configure secrets (only needed for `rift sync` + live trading):
             cp #{etc}/rift/env.example ~/.rift/.env
             $EDITOR ~/.rift/.env
             chmod 600 ~/.rift/.env

        3. Set up a wallet for live trading (when ready):
             rift auth setup

        4. Read before trading real money:
             https://github.com/Nexstone/rift/blob/main/KNOWN_ISSUES.md
             https://github.com/Nexstone/rift/blob/main/docs/AUTH_AND_EXECUTION.md

      RIFT is software, not financial advice. Trading perpetual futures
      can result in total loss of capital. The shipped `trend_follow`
      strategy is explicitly demo-only.
    EOS
  end

  test do
    # Sanity smoke — `rift --version` should print the version we installed.
    assert_match version.to_s, shell_output("#{bin}/rift --version")
    # Doctor exits non-zero only on hard failures (missing deps, broken Python).
    # We don't assert exit 0 here because doctor warns on "no wallet configured"
    # which is the expected post-install state.
    system bin/"rift", "doctor"
  end
end
