"""RIFT substrate — Layer 1 foundation.

The substrate other RIFT packages stand on. Five concerns:

  data        — access (Data.load), bar types (time / volume / dollar),
                inventory (Data.inventory), field catalog
  universe    — coin selection (HL live or from cache, sector filtering)
  frictions   — market impact, L2 slippage, latency, fees, funding cost
                (HL-calibrated, vendored defaults)
  risk        — factor decomposition, style exposure
  stats       — Sharpe/Sortino/DD with bootstrapped CIs, PSR, DSR,
                White's Reality Check, multi-comparison corrections

HL-only by design. Notebook-first Python API; CLI surfaces where natural.
Frictions and risk land incrementally.
"""

from rift_substrate.data import (
    Data,
    FieldSpec,
    FIELDS,
    InventoryReport,
)
from rift_substrate.execution import (
    BasicExit,
    ExitAction,
    ExitPolicy,
    FundingHoldExit,
    MeanReversionExit,
    PositionState,
    TrailingMomentumExit,
    resolve_policy,
)
from rift_substrate.frictions import (
    EmpiricalImpactFitter,
    FeeQuote,
    FeeSchedule,
    Fill,
    FundingAccrual,
    ImpactModel,
    ImplementationShortfall,
    L2Level,
    L2WalkResult,
    MarkoutSeries,
    SqrtLawImpact,
    TradeCost,
    accrue_funding,
    compute_markouts,
    estimate_fee,
    estimate_trade_cost,
    expected_funding_cost,
    implementation_shortfall,
    sqrt_law_impact_bps,
    walk_book,
)
from rift_substrate.indicators import (
    adx,
    atr,
    bbands,
    ema,
    macd,
    obv,
    rsi,
    sma,
    stoch,
    supertrend,
    vwap,
    wma,
    zscore,
)
from rift_substrate.regime import (
    ChangepointResult,
    HMMRegimeDetector,
    detect_changepoints,
    regime_segments,
)
from rift_substrate.risk import (
    CovarianceEstimate,
    CovarianceEstimator,
    DecompositionResult,
    DrawdownController,
    DrawdownStep,
    Factor,
    FactorModel,
    KellyResult,
    LedoitWolfCovariance,
    LimitApplicationResult,
    MarketFactor,
    MeanVarianceOptimizer,
    MomentumFactor,
    OptimizationConstraints,
    OptimizationResult,
    PositionLimits,
    RegressionResult,
    ReturnsPanel,
    SampleCovariance,
    SizeFactor,
    SizingResult,
    VolTargetResult,
    apply_limits,
    huber_regression,
    kelly_fraction_single,
    kelly_weights_multi,
    ols_with_newey_west,
    size_position,
    vol_target_position_usd,
    vol_target_scaler,
)
from rift_substrate.attribution import (
    PnLAttribution,
    ReturnsAttribution,
    attribute_pnl,
    attribute_returns,
)
from rift_substrate.backtest import (
    BacktestContext,
    BookEvent,
    EventDrivenBacktestResult,
    EventStrategy,
    ExecutionSimulator,
    FillEvent,
    OrderEvent,
    OrderSide,
    OrderType,
    TickEvent,
    run_event_driven_backtest,
)
from rift_substrate.capacity import (
    CapacityCurvePoint,
    CapacityResult,
    analyze_capacity,
    capacity_adv,
    capacity_impact,
    capacity_l2_depth,
)
from rift_substrate.cross_impact import (
    BasketImpactResult,
    basket_impact,
    correlation_matrix,
)
from rift_substrate.decay import (
    AlphaDecayCurve,
    HalfLifeFit,
    compute_ic_curve,
    estimate_half_life,
    make_forward_returns,
)
from rift_substrate.promotion import (
    GateResult,
    PromotionVerdict,
    evaluate_promotion,
    gate_capacity,
    gate_cv_pass_rate,
    gate_deflated_sharpe,
    gate_max_drawdown,
    gate_track_record,
)
from rift_substrate.signals import (
    InformationCoefficients,
    MaxIRCombiner,
    MaxIRWeights,
    OrthogonalizationResult,
    SignalScorePanel,
    information_coefficients,
    orthogonalize_signals,
)
from rift_substrate.validation import (
    CombinatoriallyPurgedCV,
    PurgedKFold,
    embargo_times,
    purge_train_indices,
)
from rift_substrate.provenance import (
    SealedBundle,
    canonical_json,
    get_git_state,
    hash_canonical_json,
    hash_data_files,
    hash_text,
    list_bundles,
    load_bundle,
    save_bundle,
    verify_bundle,
)
from rift_substrate.stats import (
    MetricBundle,
    Stats,
    bonferroni,
    benjamini_hochberg,
    deflated_sharpe_ratio,
    holm,
    periods_per_year_for_interval,
    probabilistic_sharpe_ratio,
    stationary_bootstrap,
    whites_reality_check,
)
from rift_substrate.universe import (
    AssetMetadata,
    Universe,
    UniverseSpec,
)

__all__ = [
    "AlphaDecayCurve",
    "AssetMetadata",
    "ChangepointResult",
    "BacktestContext",
    "BasicExit",
    "BasketImpactResult",
    "BookEvent",
    "CapacityCurvePoint",
    "CapacityResult",
    "CombinatoriallyPurgedCV",
    "CovarianceEstimate",
    "CovarianceEstimator",
    "Data",
    "DecompositionResult",
    "DrawdownController",
    "DrawdownStep",
    "EmpiricalImpactFitter",
    "EventDrivenBacktestResult",
    "EventStrategy",
    "ExecutionSimulator",
    "ExitAction",
    "ExitPolicy",
    "FIELDS",
    "Factor",
    "FactorModel",
    "FeeQuote",
    "FeeSchedule",
    "FieldSpec",
    "Fill",
    "FillEvent",
    "FundingAccrual",
    "FundingHoldExit",
    "GateResult",
    "HMMRegimeDetector",
    "HalfLifeFit",
    "ImpactModel",
    "ImplementationShortfall",
    "InformationCoefficients",
    "InventoryReport",
    "KellyResult",
    "L2Level",
    "L2WalkResult",
    "LedoitWolfCovariance",
    "LimitApplicationResult",
    "MarkoutSeries",
    "MarketFactor",
    "MaxIRCombiner",
    "MaxIRWeights",
    "MeanReversionExit",
    "MeanVarianceOptimizer",
    "MetricBundle",
    "MomentumFactor",
    "OptimizationConstraints",
    "OptimizationResult",
    "OrderEvent",
    "OrderSide",
    "OrderType",
    "OrthogonalizationResult",
    "PnLAttribution",
    "PositionLimits",
    "PositionState",
    "PromotionVerdict",
    "PurgedKFold",
    "RegressionResult",
    "ReturnsAttribution",
    "ReturnsPanel",
    "SampleCovariance",
    "SealedBundle",
    "SignalScorePanel",
    "SizeFactor",
    "SizingResult",
    "SqrtLawImpact",
    "Stats",
    "TickEvent",
    "TradeCost",
    "TrailingMomentumExit",
    "Universe",
    "UniverseSpec",
    "VolTargetResult",
    "accrue_funding",
    "adx",
    "analyze_capacity",
    "apply_limits",
    "atr",
    "attribute_pnl",
    "attribute_returns",
    "basket_impact",
    "bbands",
    "benjamini_hochberg",
    "bonferroni",
    "canonical_json",
    "capacity_adv",
    "capacity_impact",
    "capacity_l2_depth",
    "compute_ic_curve",
    "compute_markouts",
    "correlation_matrix",
    "deflated_sharpe_ratio",
    "detect_changepoints",
    "embargo_times",
    "ema",
    "estimate_fee",
    "estimate_half_life",
    "estimate_trade_cost",
    "evaluate_promotion",
    "expected_funding_cost",
    "gate_capacity",
    "gate_cv_pass_rate",
    "gate_deflated_sharpe",
    "gate_max_drawdown",
    "gate_track_record",
    "get_git_state",
    "hash_canonical_json",
    "hash_data_files",
    "hash_text",
    "holm",
    "huber_regression",
    "implementation_shortfall",
    "information_coefficients",
    "kelly_fraction_single",
    "kelly_weights_multi",
    "list_bundles",
    "load_bundle",
    "macd",
    "make_forward_returns",
    "obv",
    "ols_with_newey_west",
    "orthogonalize_signals",
    "periods_per_year_for_interval",
    "probabilistic_sharpe_ratio",
    "purge_train_indices",
    "regime_segments",
    "resolve_policy",
    "rsi",
    "run_event_driven_backtest",
    "save_bundle",
    "size_position",
    "sma",
    "sqrt_law_impact_bps",
    "stationary_bootstrap",
    "stoch",
    "supertrend",
    "verify_bundle",
    "vol_target_position_usd",
    "vol_target_scaler",
    "vwap",
    "walk_book",
    "whites_reality_check",
    "wma",
    "zscore",
]
